### ISSUE TITLE
Groups of agents

### ISSUE THREAD

**Issue by fatcatZF** [gaorkl/simple-playgrounds#72]
Thanks for your great work.

Is it possible to use this simulator to simulate a playground where the agents can form groups and play games together ?

**Comment by gaorkl** [comment]
Hi,

Thank you!

Yes it is possible. There is no limit on the number of agents.
I am currently working on a new versions where agents and entities can be assigned to teams. And interactive elements can only be activated by members of their own team.

Cheers

Michael
